/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { NFTReceiver, NFTReceiverInterface } from "../NFTReceiver";

const _abi = [
  {
    type: "function",
    name: "onERC721Received",
    stateMutability: "view",
    inputs: [
      {
        name: "_operator",
        type: "address",
      },
      {
        name: "_from",
        type: "address",
      },
      {
        name: "_tokenId",
        type: "uint256",
      },
    ],
    outputs: [
      {
        name: "",
        type: "bytes32",
      },
    ],
  },
  {
    type: "function",
    name: "onERC721Received",
    stateMutability: "view",
    inputs: [
      {
        name: "_operator",
        type: "address",
      },
      {
        name: "_from",
        type: "address",
      },
      {
        name: "_tokenId",
        type: "uint256",
      },
      {
        name: "_data",
        type: "bytes",
      },
    ],
    outputs: [
      {
        name: "",
        type: "bytes32",
      },
    ],
  },
  {
    type: "function",
    name: "setOwner",
    stateMutability: "nonpayable",
    inputs: [
      {
        name: "contract_address",
        type: "address",
      },
      {
        name: "_tokenId",
        type: "uint256",
      },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "withdraw",
    stateMutability: "nonpayable",
    inputs: [
      {
        name: "contract_address",
        type: "address",
      },
      {
        name: "_tokenId",
        type: "uint256",
      },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "ownerOf",
    stateMutability: "view",
    inputs: [
      {
        name: "arg0",
        type: "address",
      },
      {
        name: "arg1",
        type: "uint256",
      },
    ],
    outputs: [
      {
        name: "",
        type: "address",
      },
    ],
  },
];

export class NFTReceiver__factory {
  static readonly abi = _abi;
  static createInterface(): NFTReceiverInterface {
    return new utils.Interface(_abi) as NFTReceiverInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): NFTReceiver {
    return new Contract(address, _abi, signerOrProvider) as NFTReceiver;
  }
}
