/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { useMemo } from 'react'

import {
  CallResult,
  useCall,
  useContractFunction,
  useEthers,
} from '@usedapp/core'
import { ContractFunctionNames } from '@usedapp/core/dist/esm/src/model/types'

import getContract from '../getContract'
import { ToDoMethodNames } from '../requests'
import { ToDo } from '../typechain'

export function useToDoCall<M extends ToDoMethodNames>(
  method: M,
  args: Parameters<ToDo['functions'][M]>,
) {
  const { chainId } = useEthers()

  const contract = useMemo(() => getContract('ToDo', chainId), [chainId])

  const { value, error } = (useCall({
    contract,
    method,
    args,
  }) as CallResult<ToDo, M>) ?? {
    value: undefined,
    error: undefined,
  }

  return [value?.[0], error, !value] as [
    Awaited<ReturnType<ToDo['functions'][M]>>[0] | undefined,
    Error | undefined,
    boolean,
  ]
}

type ToDoFunctions = ContractFunctionNames<ToDo>
export function useToDoFunction(name: ToDoFunctions, transactionName?: string) {
  const { chainId } = useEthers()

  const contract = useMemo(() => getContract('ToDo', chainId), [chainId])

  const transaction = useContractFunction(contract, name, {
    transactionName: transactionName || name,
  })
  return transaction
}
